version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            sudo apt-get update && sudo apt-get install wget zip unzip python-pip python-dev build-essential -y
            python --version
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Build Artifact
          command: |
            pwd
            ls -al
            gradle buildLambdaZip
            cd build/distributions
            pwd
            ls -al
            cd ../../..
      - run:
          name: Update zip in lambda function
          command: |
            aws lambda update-function-code --region=${AWS_REGION} --function-name=SendEmail  --zip-file fileb://build/distributions/lambda-1.0-SNAPSHOT.zip

workflows:
  version: 2
  build_deploy_lambda-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master